import "./globals.css";


export const metadata = {
  title: "En Uygun Kredi Hesaplama Aracı",
  description: "Generated by erdemarslan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body >{children}</body>
    </html>
  );
}
